# новый оптимизатор ключевых слов
keywords = input()
keywords = keywords.replace("?","й")
keywords = keywords.replace(",","*")
keywords = keywords.replace("|","*")
keywords = keywords.replace(";","*")
keywords = keywords.replace("  ","*")
keywords = keywords.replace(" ","*")
keywords = keywords.replace(".","*")
# print(keywords)
b = set(keywords.split("*"))
b = sorted(b)
# print(b)
print(", ".join(b))